
name: CI

on:
  push:
    branches: [ "test_ci" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: List all files
        run: ls

      - name: Install Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: Install connector 
        run: pip install snowflake-connector-python --upgrade

      - name: Install pandas 
        run: pip install pandas --upgrade

      - name: Install pandas snowflake
        run: pip install snowflake-connector-python[pandas] --upgrade

      - name: Install dotenv
        run: pip install python-dotenv
      # - name: Run Python Script
      #   run: python create_file.py
      - name: Create env file
        run: |
          touch .env
          echo  SF_ACCOUNT:  $(SF_ACCOUNT) >> .env
          echo SF_USERNAME: $(SF_USERNAME) >> .env
          echo SF_PASSWORD: $(SF_PASSWORD) >> .env
          echo: SF_USERNAME

  


